clusterName: capi-prod
clusterNamespace: default
gcpProject: p-22s7pdmwkw8s-0
gcpRegion: europe-west1
gcpControlPlaneInstanceType: e2-standard-2
gcpWorkerInstanceType: e2-standard-2
gcpImageProject: nic-dev-356208
gcpImage: cluster-api-ubuntu-2004-v1-26-3-1679528631
controlPlaneReplicas: 1
workerReplicas: 1
maxWorkerReplicas: 10
kubernetesVersion: 1.26.3
addons:
  nginxIngressChart: enabled
  calicoCNIChart: enabled

